create user api identified by root;

grant connect, resource to api;


 --------------------------------------------------------
--  Arquivo criado - Sexta-feira-Dezembro-29-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table MENSAGEM
--------------------------------------------------------

  CREATE TABLE "API"."MENSAGEM" 
   (	"ID" NUMBER(19,0), 
	"CONTEUDO" VARCHAR2(255 BYTE), 
	"FONTE" VARCHAR2(255 BYTE), 
	"IDTWITTER" NUMBER(19,0), 
	"MAIORES" VARCHAR2(255 BYTE), 
	"MEDIA" FLOAT(126), 
	"MENORES" VARCHAR2(255 BYTE), 
	"NUMEROPALAVRAS" NUMBER(10,0), 
	"TAMANHOMAISCURTA" NUMBER(10,0), 
	"TAMANHOMAISLONGA" NUMBER(10,0), 
	"USUARIO" VARCHAR2(255 BYTE), 
	"MAISCOMUM" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PALAVRA
--------------------------------------------------------

  CREATE TABLE "API"."PALAVRA" 
   (	"ID" NUMBER(19,0), 
	"VALOR" VARCHAR2(255 BYTE), 
	"MENSAGEM_ID" NUMBER(19,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007032
--------------------------------------------------------

  CREATE UNIQUE INDEX "API"."SYS_C007032" ON "API"."MENSAGEM" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007034
--------------------------------------------------------

  CREATE UNIQUE INDEX "API"."SYS_C007034" ON "API"."PALAVRA" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table MENSAGEM
--------------------------------------------------------

  ALTER TABLE "API"."MENSAGEM" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "API"."MENSAGEM" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PALAVRA
--------------------------------------------------------

  ALTER TABLE "API"."PALAVRA" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "API"."PALAVRA" MODIFY ("ID" NOT NULL ENABLE);
